is.num = (a) => typeof a === 'number';
is.nan = (a) => Number.isNaN(a);
is.str = (a) => typeof a === 'string';
is.bool = (a) => typeof a === 'boolean';
is.undef = (a) => typeof a === 'undefined';
is.def = (a) => typeof a !== 'undefined';
is.arr = (a) => Array.isArray(a);
is.fun = (a) => typeof a === 'function';
is.truthy = (a) => !!a;
is.falsy = (a) => !a;
is.obj = function (a) { return (typeof a === 'object' && !!a && !Array.isArray(a)) };